#
#spring:
#  application:
#    name: hms-api-gateway
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
#      mvc:
#        routes:
#         predicates:
#           - Path=/api/v1/room/**  # Ensure the path matches what you're trying to hit
#         filters:
#           - StripPrefix=2  # Adjusts the URL path as needed by your service
#server:
#  port: 8080
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
